// SPDX-License-Identifier: NONE
// AUTO-GENERATED by tools/migration/t14_tilesets_port.py
// Phase 4 R5f - HnS Johto/Kanto tilesets additive port (HMS Hood).
// Do not edit by hand; rerun the tool to regenerate.

// Tileset tiles + palette arrays from HnS Johto/Kanto.

const u32 gTilesetTiles_AzaleaTown[] = INCBIN_U32("data/tilesets/secondary/azalea_town/tiles.4bpp.lz");

const u32 gTilesetTiles_Barn[] = INCBIN_U32("data/tilesets/secondary/barn/tiles.4bpp.lz");

const u32 gTilesetTiles_BellchimeTrail[] = INCBIN_U32("data/tilesets/secondary/bellchime_trail/tiles.4bpp.lz");

const u32 gTilesetTiles_Blackthorn[] = INCBIN_U32("data/tilesets/secondary/blackthorn/tiles.4bpp.lz");

const u32 gTilesetTiles_BlackthornGym[] = INCBIN_U32("data/tilesets/secondary/blackthorn_gym/tiles.4bpp.lz");

const u32 gTilesetTiles_BurnedTower[] = INCBIN_U32("data/tilesets/secondary/burned_tower/tiles.4bpp.lz");

const u32 gTilesetTiles_Cafe[] = INCBIN_U32("data/tilesets/secondary/cafe/tiles.4bpp.lz");

const u32 gTilesetTiles_Cave_Default[] = INCBIN_U32("data/tilesets/secondary/cave_default/tiles.4bpp.lz");

const u32 gTilesetTiles_Cave_DragonsDen[] = INCBIN_U32("data/tilesets/secondary/cave_dragons_den/tiles.4bpp.lz");

const u32 gTilesetTiles_Cave_Gray[] = INCBIN_U32("data/tilesets/secondary/cave_gray/tiles.4bpp.lz");

const u32 gTilesetTiles_Cave_Green[] = INCBIN_U32("data/tilesets/secondary/cave_green/tiles.4bpp.lz");

const u32 gTilesetTiles_Cave_Ice[] = INCBIN_U32("data/tilesets/secondary/cave_ice/tiles.4bpp.lz");

const u32 gTilesetTiles_Cave_MtMoon[] = INCBIN_U32("data/tilesets/secondary/cave_mt_moon/tiles.4bpp.lz");

const u32 gTilesetTiles_Cave_Sandy[] = INCBIN_U32("data/tilesets/secondary/cave_sandy/tiles.4bpp.lz");

const u32 gTilesetTiles_CeladonApartments[] = INCBIN_U32("data/tilesets/secondary/celadon_apartments/tiles.4bpp.lz");

const u32 gTilesetTiles_CeruleanCity_Gym[] = INCBIN_U32("data/tilesets/secondary/cerulean_city_gym/tiles.4bpp.lz");

const u32 gTilesetTiles_CherrygroveCity[] = INCBIN_U32("data/tilesets/secondary/cherrygrove_city/tiles.4bpp.lz");

const u32 gTilesetTiles_CianwoodCity[] = INCBIN_U32("data/tilesets/secondary/cianwood_city/tiles.4bpp.lz");

const u32 gTilesetTiles_CianwoodCity_Gym[] = INCBIN_U32("data/tilesets/secondary/cianwood_city_gym/tiles.4bpp.lz");

const u32 gTilesetTiles_CyclingRoad[] = INCBIN_U32("data/tilesets/secondary/cycling_road/tiles.4bpp.lz");

const u32 gTilesetTiles_DragonsDen_Shrine[] = INCBIN_U32("data/tilesets/secondary/dragons_den_shrine/tiles.4bpp.lz");

const u32 gTilesetTiles_EcruteakCity_Gym[] = INCBIN_U32("data/tilesets/secondary/ecruteak_city_gym/tiles.4bpp.lz");

const u32 gTilesetTiles_EcruteakTheater[] = INCBIN_U32("data/tilesets/secondary/ecruteak_theater/tiles.4bpp.lz");

const u32 gTilesetTiles_Ecruteak_City[] = INCBIN_U32("data/tilesets/secondary/ecruteak_city/tiles.4bpp.lz");

const u32 gTilesetTiles_Fuchsia[] = INCBIN_U32("data/tilesets/secondary/fuchsia/tiles.4bpp.lz");

const u32 gTilesetTiles_FuchsiaCity_Gym[] = INCBIN_U32("data/tilesets/secondary/fuchsia_city_gym/tiles.4bpp.lz");

const u32 gTilesetTiles_Gate_Standard[] = INCBIN_U32("data/tilesets/secondary/gate_standard/tiles.4bpp.lz");

const u32 gTilesetTiles_Goldenrod[] = INCBIN_U32("data/tilesets/secondary/goldenrod/tiles.4bpp.lz");

const u32 gTilesetTiles_GoldenrodCity_TrainStation[] = INCBIN_U32("data/tilesets/secondary/goldenrod_station/tiles.4bpp.lz");

const u32 gTilesetTiles_GoldenrodUndergroundRocket[] = INCBIN_U32("data/tilesets/secondary/goldenrod_underground_rocket/tiles.4bpp.lz");

const u32 gTilesetTiles_GoldenrodUndergroundTunnel[] = INCBIN_U32("data/tilesets/secondary/goldenrod_underground_tunnel/tiles.4bpp.lz");

const u32 gTilesetTiles_Goldenrod_Underground_Storage[] = INCBIN_U32("data/tilesets/secondary/goldenrod_underground_storage/tiles.4bpp.lz");

const u32 gTilesetTiles_House_2[] = INCBIN_U32("data/tilesets/secondary/house_2/tiles.4bpp.lz");

const u32 gTilesetTiles_House_Lab[] = INCBIN_U32("data/tilesets/secondary/house_lab/tiles.4bpp.lz");

const u32 gTilesetTiles_IlexForest[] = INCBIN_U32("data/tilesets/secondary/ilex_forest/tiles.4bpp.lz");

const u32 gTilesetTiles_JohtoBikeShop[] = INCBIN_U32("data/tilesets/secondary/johto_bike_shop/tiles.4bpp.lz");

const u32 gTilesetTiles_JohtoMart[] = INCBIN_U32("data/tilesets/secondary/johto_mart/tiles.4bpp.lz");

const u32 gTilesetTiles_Johto_Building[] = INCBIN_U32("data/tilesets/primary/johto_building/tiles.4bpp.lz");

const u32 gTilesetTiles_Johto_General[] = INCBIN_U32("data/tilesets/primary/johto_general/tiles.4bpp.lz");

const u32 gTilesetTiles_Johto_NorthEast[] = INCBIN_U32("data/tilesets/primary/johto_north_east/tiles.4bpp.lz");

const u32 gTilesetTiles_Johto_NorthWest[] = INCBIN_U32("data/tilesets/primary/johto_north_west/tiles.4bpp.lz");

const u32 gTilesetTiles_Johto_South[] = INCBIN_U32("data/tilesets/primary/johto_south/tiles.4bpp.lz");

const u32 gTilesetTiles_KantoMart[] = INCBIN_U32("data/tilesets/secondary/kanto_mart/tiles.4bpp.lz");

const u32 gTilesetTiles_Kanto_Building[] = INCBIN_U32("data/tilesets/primary/kanto_building/tiles.4bpp.lz");

const u32 gTilesetTiles_Kanto_General[] = INCBIN_U32("data/tilesets/primary/kanto_general/tiles.4bpp.lz");

const u32 gTilesetTiles_Kanto_PokemonCenter[] = INCBIN_U32("data/tilesets/secondary/kanto_pokemon_center/tiles.4bpp.lz");

const u32 gTilesetTiles_KurtsHouse[] = INCBIN_U32("data/tilesets/secondary/kurts_house/tiles.4bpp.lz");

const u32 gTilesetTiles_Lighthouse[] = INCBIN_U32("data/tilesets/secondary/lighthouse/tiles.4bpp.lz");

const u32 gTilesetTiles_MahoganyTown[] = INCBIN_U32("data/tilesets/secondary/mahogany_town/tiles.4bpp.lz");

const u32 gTilesetTiles_MtSilverSnow[] = INCBIN_U32("data/tilesets/secondary/mt_silver_snow/tiles.4bpp.lz");

const u32 gTilesetTiles_NationalPark[] = INCBIN_U32("data/tilesets/secondary/national_park/tiles.4bpp.lz");

const u32 gTilesetTiles_NewBarkTown[] = INCBIN_U32("data/tilesets/secondary/new_bark_town/tiles.4bpp.lz");

const u32 gTilesetTiles_OlivineCity[] = INCBIN_U32("data/tilesets/secondary/olivine_city/tiles.4bpp.lz");

const u32 gTilesetTiles_PlayersHouse[] = INCBIN_U32("data/tilesets/secondary/players_house/tiles.4bpp.lz");

const u32 gTilesetTiles_PokemonCenter_White[] = INCBIN_U32("data/tilesets/secondary/pokemon_center_white/tiles.4bpp.lz");

const u32 gTilesetTiles_PortIndoor[] = INCBIN_U32("data/tilesets/secondary/port_indoor/tiles.4bpp.lz");

const u32 gTilesetTiles_PowerPlant_GeneratorRoom[] = INCBIN_U32("data/tilesets/secondary/power_plant_generator_room/tiles.4bpp.lz");

const u32 gTilesetTiles_Route32[] = INCBIN_U32("data/tilesets/secondary/route_32/tiles.4bpp.lz");

const u32 gTilesetTiles_Route38_Farmland[] = INCBIN_U32("data/tilesets/secondary/route38_farmland/tiles.4bpp.lz");

const u32 gTilesetTiles_RuinsOfAlphWriting[] = INCBIN_U32("data/tilesets/secondary/ruins_of_alph_writing/tiles.4bpp.lz");

const u32 gTilesetTiles_RuinsOfAlph_B1F[] = INCBIN_U32("data/tilesets/secondary/ruins_of_alph_b1_f/tiles.4bpp.lz");

const u32 gTilesetTiles_RuinsOfAlph_Outside[] = INCBIN_U32("data/tilesets/secondary/ruins_of_alph_outside/tiles.4bpp.lz");

const u32 gTilesetTiles_SafariZoneJohto[] = INCBIN_U32("data/tilesets/secondary/safari_zone_johto/tiles.4bpp.lz");

const u32 gTilesetTiles_SafariZone_Entrance[] = INCBIN_U32("data/tilesets/secondary/safari_zone_entrance/tiles.4bpp.lz");

const u32 gTilesetTiles_SaffronCity_FightingDojoVIP[] = INCBIN_U32("data/tilesets/secondary/saffron_city_dojo_vip/tiles.4bpp.lz");

const u32 gTilesetTiles_SaffronCity_Gym[] = INCBIN_U32("data/tilesets/secondary/saffron_city_gym/tiles.4bpp.lz");

const u32 gTilesetTiles_ShopRooftop[] = INCBIN_U32("data/tilesets/secondary/shop_rooftop/tiles.4bpp.lz");

const u32 gTilesetTiles_SoulHouse[] = INCBIN_U32("data/tilesets/secondary/soul_house/tiles.4bpp.lz");

const u32 gTilesetTiles_TrainerHill_Courtyard[] = INCBIN_U32("data/tilesets/secondary/battle_tower_outer/tiles.4bpp.lz");

const u32 gTilesetTiles_TrainerSchool[] = INCBIN_U32("data/tilesets/secondary/trainer_school/tiles.4bpp.lz");

const u32 gTilesetTiles_Unused3[] = INCBIN_U32("data/tilesets/secondary/unused3/tiles.4bpp.lz");

const u32 gTilesetTiles_Vermilion[] = INCBIN_U32("data/tilesets/secondary/vermilion/tiles.4bpp.lz");

const u32 gTilesetTiles_VermilionCity_Gym[] = INCBIN_U32("data/tilesets/secondary/vermilion_city_gym/tiles.4bpp.lz");

const u32 gTilesetTiles_VioletCity[] = INCBIN_U32("data/tilesets/secondary/violet_city/tiles.4bpp.lz");

const u32 gTilesetTiles_ViridianCity_Gym[] = INCBIN_U32("data/tilesets/secondary/viridian_city_gym/tiles.4bpp.lz");

const u32 gTilesetTiles_WhirlIslands[] = INCBIN_U32("data/tilesets/secondary/whirl_islands/tiles.4bpp.lz");

const u32 gTilesetTiles_azalea_town_gym[] = INCBIN_U32("data/tilesets/secondary/azalea_town_gym/tiles.4bpp.lz");

const u32 gTilesetTiles_ssaqua[] = INCBIN_U32("data/tilesets/secondary/ssaqua/tiles.4bpp.lz");

const u16 gTilesetPalettes_AzaleaTown[][16] =
{
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Barn[][16] =
{
    INCBIN_U16("data/tilesets/secondary/barn/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/barn/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_BellchimeTrail[][16] =
{
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/bellchime_trail/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Blackthorn[][16] =
{
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_BlackthornGym[][16] =
{
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/blackthorn_gym/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_BurnedTower[][16] =
{
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/burned_tower/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Cafe[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cafe/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Cave_Default[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_default/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Cave_DragonsDen[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_dragons_den/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Cave_Gray[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_gray/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Cave_Green[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_green/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Cave_Ice[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_ice/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Cave_MtMoon[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_mt_moon/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Cave_Sandy[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cave_sandy/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_CeladonApartments[][16] =
{
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/celadon_apartments/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_CeruleanCity_Gym[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cerulean_city_gym/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_CherrygroveCity[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cherrygrove_city/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_CianwoodCity[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_CianwoodCity_Gym[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cianwood_city_gym/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_CyclingRoad[][16] =
{
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/cycling_road/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_DragonsDen_Shrine[][16] =
{
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/dragons_den_shrine/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_EcruteakCity_Gym[][16] =
{
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city_gym/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_EcruteakTheater[][16] =
{
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_theater/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Ecruteak_City[][16] =
{
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ecruteak_city/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Fuchsia[][16] =
{
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_FuchsiaCity_Gym[][16] =
{
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/fuchsia_city_gym/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Gate_Standard[][16] =
{
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/gate_standard/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Goldenrod[][16] =
{
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_GoldenrodCity_TrainStation[][16] =
{
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_station/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_GoldenrodUndergroundRocket[][16] =
{
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_rocket/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_GoldenrodUndergroundTunnel[][16] =
{
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_tunnel/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Goldenrod_Underground_Storage[][16] =
{
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/goldenrod_underground_storage/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_House_2[][16] =
{
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_2/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_House_Lab[][16] =
{
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/house_lab/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_IlexForest[][16] =
{
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ilex_forest/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_JohtoBikeShop[][16] =
{
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_bike_shop/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_JohtoMart[][16] =
{
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/johto_mart/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Johto_Building[][16] =
{
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_building/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Johto_General[][16] =
{
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_general/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Johto_NorthEast[][16] =
{
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_east/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Johto_NorthWest[][16] =
{
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_north_west/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Johto_South[][16] =
{
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/primary/johto_south/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_KantoMart[][16] =
{
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Kanto_Building[][16] =
{
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_building/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Kanto_General[][16] =
{
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Kanto_PokemonCenter[][16] =
{
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_KurtsHouse[][16] =
{
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kurts_house/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Lighthouse[][16] =
{
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/lighthouse/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_MahoganyTown[][16] =
{
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mahogany_town/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_MtSilverSnow[][16] =
{
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/mt_silver_snow/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_NationalPark[][16] =
{
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/national_park/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_NewBarkTown[][16] =
{
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/new_bark_town/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_OlivineCity[][16] =
{
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/olivine_city/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_PlayersHouse[][16] =
{
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/players_house/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_PokemonCenter_White[][16] =
{
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/pokemon_center_white/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_PortIndoor[][16] =
{
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/port_indoor/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_PowerPlant_GeneratorRoom[][16] =
{
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/power_plant_generator_room/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Route32[][16] =
{
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route_32/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Route38_Farmland[][16] =
{
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/route38_farmland/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_RuinsOfAlphWriting[][16] =
{
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_writing/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_RuinsOfAlph_B1F[][16] =
{
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_b1_f/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_RuinsOfAlph_Outside[][16] =
{
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ruins_of_alph_outside/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_SafariZoneJohto[][16] =
{
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_johto/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_SafariZone_Entrance[][16] =
{
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/safari_zone_entrance/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_SaffronCity_FightingDojoVIP[][16] =
{
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_dojo_vip/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_SaffronCity_Gym[][16] =
{
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/saffron_city_gym/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_ShopRooftop[][16] =
{
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/shop_rooftop/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_SoulHouse[][16] =
{
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/soul_house/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_TrainerHill_Courtyard[][16] =
{
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/battle_tower_outer/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_TrainerSchool[][16] =
{
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/trainer_school/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Unused3[][16] =
{
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/unused3/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_Vermilion[][16] =
{
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_VermilionCity_Gym[][16] =
{
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/vermilion_city_gym/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_VioletCity[][16] =
{
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/violet_city/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_ViridianCity_Gym[][16] =
{
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/viridian_city_gym/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_WhirlIslands[][16] =
{
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/whirl_islands/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_azalea_town_gym[][16] =
{
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/azalea_town_gym/palettes/12.gbapal"),
};

const u16 gTilesetPalettes_ssaqua[][16] =
{
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/ssaqua/palettes/12.gbapal"),
};

