// SPDX-License-Identifier: NONE
// AUTO-GENERATED by tools/migration/t14_tilesets_port.py
// Phase 4 R5f - HnS Johto/Kanto tilesets extern declarations.

#ifndef GUARD_TILESETS_HNS_H
#define GUARD_TILESETS_HNS_H

extern const struct Tileset gTileset_AzaleaTown;
extern const struct Tileset gTileset_AzaleaTown_Gym;
extern const struct Tileset gTileset_Barn;
extern const struct Tileset gTileset_BellchimeTrail;
extern const struct Tileset gTileset_Blackthorn;
extern const struct Tileset gTileset_BlackthornGym;
extern const struct Tileset gTileset_BurnedTower;
extern const struct Tileset gTileset_Cafe;
extern const struct Tileset gTileset_Cave_Default;
extern const struct Tileset gTileset_Cave_DragonsDen;
extern const struct Tileset gTileset_Cave_Gray;
extern const struct Tileset gTileset_Cave_Green;
extern const struct Tileset gTileset_Cave_Ice;
extern const struct Tileset gTileset_Cave_MtMoon;
extern const struct Tileset gTileset_Cave_Sandy;
extern const struct Tileset gTileset_CeladonApartments;
extern const struct Tileset gTileset_CeruleanCity_Gym;
extern const struct Tileset gTileset_CherrygroveCity;
extern const struct Tileset gTileset_CianwoodCity;
extern const struct Tileset gTileset_CianwoodCity_Gym;
extern const struct Tileset gTileset_CyclingRoad;
extern const struct Tileset gTileset_DragonsDen_Shrine;
extern const struct Tileset gTileset_EcruteakCity_Gym;
extern const struct Tileset gTileset_EcruteakTheater;
extern const struct Tileset gTileset_Ecruteak_City;
extern const struct Tileset gTileset_Fuchsia;
extern const struct Tileset gTileset_FuchsiaCity_Gym;
extern const struct Tileset gTileset_Gate_Standard;
extern const struct Tileset gTileset_Goldenrod;
extern const struct Tileset gTileset_GoldenrodCity_TrainStation;
extern const struct Tileset gTileset_GoldenrodUndergroundRocket;
extern const struct Tileset gTileset_GoldenrodUndergroundTunnel;
extern const struct Tileset gTileset_Goldenrod_Underground_Storage;
extern const struct Tileset gTileset_House_2;
extern const struct Tileset gTileset_House_Lab;
extern const struct Tileset gTileset_IlexForest;
extern const struct Tileset gTileset_JohtoBikeShop;
extern const struct Tileset gTileset_JohtoMart;
extern const struct Tileset gTileset_Johto_Building;
extern const struct Tileset gTileset_Johto_General;
extern const struct Tileset gTileset_Johto_NorthEast;
extern const struct Tileset gTileset_Johto_NorthWest;
extern const struct Tileset gTileset_Johto_South;
extern const struct Tileset gTileset_KantoMart;
extern const struct Tileset gTileset_Kanto_Building;
extern const struct Tileset gTileset_Kanto_General;
extern const struct Tileset gTileset_Kanto_PokemonCenter;
extern const struct Tileset gTileset_KurtsHouse;
extern const struct Tileset gTileset_Lighthouse;
extern const struct Tileset gTileset_MahoganyTown;
extern const struct Tileset gTileset_MtSilverSnow;
extern const struct Tileset gTileset_NationalPark;
extern const struct Tileset gTileset_NewBarkTown;
extern const struct Tileset gTileset_OlivineCity;
extern const struct Tileset gTileset_PlayersHouse;
extern const struct Tileset gTileset_PokemonCenter_White;
extern const struct Tileset gTileset_PortIndoor;
extern const struct Tileset gTileset_PowerPlant_GeneratorRoom;
extern const struct Tileset gTileset_Route32;
extern const struct Tileset gTileset_Route38_Farmland;
extern const struct Tileset gTileset_RuinsOfAlphWriting;
extern const struct Tileset gTileset_RuinsOfAlph_B1F;
extern const struct Tileset gTileset_RuinsOfAlph_Outside;
extern const struct Tileset gTileset_SafariZoneJohto;
extern const struct Tileset gTileset_SafariZone_Entrance;
extern const struct Tileset gTileset_SaffronCity_FightingDojoVIP;
extern const struct Tileset gTileset_SaffronCity_Gym;
extern const struct Tileset gTileset_ShopRooftop;
extern const struct Tileset gTileset_SoulHouse;
extern const struct Tileset gTileset_TrainerHill_Courtyard;
extern const struct Tileset gTileset_TrainerSchool;
extern const struct Tileset gTileset_Unused3;
extern const struct Tileset gTileset_Vermilion;
extern const struct Tileset gTileset_VermilionCity_Gym;
extern const struct Tileset gTileset_VioletCity;
extern const struct Tileset gTileset_ViridianCity_Gym;
extern const struct Tileset gTileset_WhirlIslands;
extern const struct Tileset gTileset_ssaqua;

#endif // GUARD_TILESETS_HNS_H
